### ISSUE TITLE
Article without a first-publisher DOI, only re-publisher DOI

### ISSUE THREAD

**Issue by hsh-bib** [OpenAPC/openapc-de#1439]
Last year, we financed an article that did not attach a DOI to a published article. The publisher solely uses the URN system as an identifier. We attached a first DOI to the article after the fact when we re-published the article on our institutional document server.

In our CSV file for 2022 I plan to add the DOI of our re-published version and fill out the CSV field `publisher`. The latter in order to hopefully attach the correct label of the publisher's name on the treemap visualisation - not the incorrect "Hochschule Hannover", since the re-published DOI points to us. My datum as of now is as follows:

```
institution,period,euro,doi,is_hybrid,publisher,,,
Hochschule Hannover,2022,402.22,10.25968/opus-2321,FALSE,RonPub UG,,,
```

Am I correct in my assumption that I can correctly add and attribute the article to its first-publisher as lined out?

**Comment by cbroschinski** [comment]
Yes, that will work. 
Our enrichment workflow looks up the DOI in Crossref to obtain the publisher/journal title combo, which will then overwrite the data in the submitted file. If the DOI is not registered with Crossref (as it's the case with your example), the original data (RonPub UG) will be kept instead. You could, however, still improve your data by also adding `journal_full_title` and `issn` for the record in question, as these are also mandatory fields. Since those cannot be obtained from Crossref, we would have to add them manually during processing otherwise.

**Comment by hsh-bib** [comment]
Thank you for your information. I will keep adding the additional data in mind while finishing up our data delivery.
