### ISSUE TITLE
Poster fees in OpenAPC 

### ISSUE THREAD

**Issue by adrsik** [OpenAPC/openapc-de#149]
We cover also poster fees for Max Planck researchers published OA from ScienceOpen.
Here an example: https://www.scienceopen.com/document?vid=dbbfbfe7-e0ae-427e-b000-5fc4a0a2a5f3
Should we add poster APC also to the data set?

**Comment by cbroschinski** [comment]
Interesting idea, but I do not think so. We already had some cases of book chapters in our data contributions ([INTECH](http://www.intechopen.com), for example, publishes open books and charges processing fees for book chapters comparable to Journal APCs) and we also decided to exclude them, since our data schema simply is not suited to that case (ISBN instead of ISSN, book title vs journal title, no pubmed/DOAJ metadata etc). Poster fees would likely pose similar problems. We should avoid those by strictly keeping to the 'A' in OpenAPC :)
