### ISSUE TITLE
Articles w/o DOI

### ISSUE THREAD

**Issue by tullney** [OpenAPC/openapc-de#54]
The sample CSV file has a DOI column, it is assumed that every article has a DOI assigned to it. Information and workflow is needed for cases where this is not true (e.g. leave column empty, add URL instead, etc.).

**Comment by njahn82** [comment]
yes, that would help a lot. So far, add in the doi column `NA`and add manually as much information as possible

**Comment by cbroschinski** [comment]
We discussed that issue on the Hannover hackday. However, as I am now up to implement it in the semi-automatic python script, this is still not entirely clear to me.
According to our new data schema (https://github.com/OpenAPC/openapc-de/wiki/schema), every entry not featuring a DOI has to contain the set of 'optional' fields instead (publisher, journal_full_title, the 3 ISSNs and url). Especially the ISSN case seems problematic. Do we really require all 3 of them to be present?

**Comment by tullney** [comment]
If there is no DOI, I suggest treating these values as mandatory:
* `publisher`
* `journal_full_title`
* `url`

and maybe `issn` (not all three of them)

**Comment by njahn82** [comment]
Yes, this makes sense. I will change it. Thanks!

**Comment by njahn82** [comment]
changed https://github.com/OpenAPC/openapc-de/wiki/schema

**Comment by cbroschinski** [comment]
I have just edited 
https://github.com/OpenAPC/openapc-de/wiki/Handreichung-Dateneingabe
to reflect our new standards. I would also like to point out that we received our first contribution were the discussed case came into effect: 
https://github.com/OpenAPC/openapc-de/blob/v2.1.4/data/uniheidelberg/openAPC_Datenlieferung_2015.csv (last 3 entries)
My python scripts have also been adapted accordingly. To my mind, this issue is settled.
