### ISSUE TITLE
Update UTs

### ISSUE THREAD

**Issue by njahn82** [OpenAPC/openapc-de#76]

**Comment by vpeil** [comment]
@cbroschinski let's think about a nice mechenaism...

**Comment by vpeil** [comment]
@njahn82 It would have been finished if not for the inconsistent quotation rules in the datastet.... let me explain:

the current quotation rule does not meet any standards like "minimial quotation" in perl / python
nor does it use the "always quote" option.

Can we agree on one of the above?
("Do not quote the columns 'euro' and 'period' and none of the fields with value NA." is not nice)
The change may have some impact on existing R scripts.

**Comment by cbroschinski** [comment]
To be precise: The current rules for the apc_de main files are "Do not quote the columns euro and period and do not quote the values NA, TRUE and FALSE. Quote everything else". And yes, I agree that this peculiar quotation style makes working on the file quite difficult.

**Comment by njahn82** [comment]
Well, the conventions reflect how R is  handling vectors of different types, which is necessary for analytical re-use of the data. 

So either you rewrite the analytical components in the programming language of your choice while ensuring re-use or you give R a try. By the way, did you know, that you can also run R within Python and Perl code? However, will look what this "minimal quotation" is about and can be implemented.

Here is how the csv is structured in R after import.

```
## 'data.frame':	5645 obs. of  17 variables:
##  $ institution        : Factor w/ 29 levels "Bamberg U","Bayreuth U",..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ period             : int  2013 2013 2013 2013 2013 2013 2013 2013 2013 2013 ...
##  $ euro               : num  1372 960 960 960 182 ...
##  $ doi                : Factor w/ 5615 levels "10.1002/2014MS000376",..: 3974 4459 4468 4474 NA 131 3376 3409 5519 1269 ...
##  $ is_hybrid          : logi  FALSE FALSE FALSE FALSE FALSE FALSE ...
##  $ publisher          : Factor w/ 114 levels "Academic Journals",..: 28 44 44 44 70 83 85 85 92 103 ...
##  $ journal_full_title : Factor w/ 607 levels "Acta Crystallographica Section E Crystallographic Communications",..: 402 264 264 264 316 340 529 529 325 110 ...
##  $ issn               : Factor w/ 600 levels "0001-5555","0013-9998",..: 47 196 196 196 344 388 346 346 342 88 ...
##  $ issn_print         : Factor w/ 362 levels "","0001-5555",..: NA NA NA NA NA NA NA NA 239 67 ...
##  $ issn_electronic    : Factor w/ 398 levels "0974276X","0975900X",..: 13 131 131 131 NA 250 219 219 217 NA ...
##  $ license_ref        : Factor w/ 13 levels "http://creativecommons.org/licenses/by/3.0/",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ indexed_in_crossref: logi  TRUE TRUE TRUE TRUE FALSE TRUE ...
##  $ pmid               : Factor w/ 3731 levels "18380896","18479523",..: NA 1582 1661 1695 NA 2053 1890 2051 NA 2033 ...
##  $ pmcid              : Factor w/ 3620 levels "PMC2311307","PMC2396600",..: NA 1510 1594 1625 NA 1941 1805 1936 NA 2520 ...
##  $ ut                 : Factor w/ 2970 levels "ut:000207491700001",..: NA 1726 1741 1752 NA 2140 1389 1529 NA 1586 ...
##  $ url                : Factor w/ 3 levels "http://vabnagarfoundation.com/bhabnagar-2nd-volume-april-2015",..: NA NA NA NA NA NA NA NA NA NA ...
##  $ doaj               : logi  TRUE TRUE TRUE TRUE FALSE TRUE ...
```

**Comment by njahn82** [comment]
have you tried this, @vpeil 

http://search.cpan.org/~limaone/Text-CSV-R-0.3/lib/Text/CSV/R.pm

**Comment by njahn82** [comment]
Have you tried the pandas library, @cbroschinski ?
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html

**Comment by cbroschinski** [comment]
@njahn82 There's no problem on my side, I have already implemented a custom CSV reader/writer in python to mimic the specific R style. But @vpeil is trying to adapt his perl code at the moment to directly enrich the apc file with the WoS ut.

**Comment by cbroschinski** [comment]
@njahn82 It seems there's an argument called colClasses you can provide to read.csv to specify the data type of every csv column:
https://stackoverflow.com/questions/2805357/specifying-colclasses-in-the-read-csv
So keeping the current quoting schema is only necessary if you want to rely on calling read.csv() with automatic type detection.
However, I strongly propose to change to a more generic quote schema: Simply quote everything. It is easily the most robust behaviour (Remember, we are dealing with a lot of possible fields were separator chars (. , ;) might appear (euro values, journal titles, publisher names) and it is also the most simple. Furthermore, it is a format almost every half-decent CSV library on this planet should be able to parse. And since this an Open Data project, I think we should be as programming language-agnostic as possible and not enforce people to use R for data reuse.

**Comment by njahn82** [comment]
Decimals in euro are always points `.` Journal and Publisher are in enquoted. I also cannot see, why the standard R csv export is not programming language-agnostic; you can open it in python, too. I can even open it in Excel  ...

A generic way to provide information about classes can be found here:

http://data.okfn.org/standards

Wonder, if it answers Vitalis need.

**Comment by vpeil** [comment]
btw: happy birthday.

**Comment by vpeil** [comment]
well, the R-style quotation is language-agnostic. I can read it in Perl (and I think the same is true for Python). But the point here is: it's hard to produce ("write") such a csv file in R-style with non-R-tools

**Comment by vpeil** [comment]
I like the idea of OKFN data packages and I think we already discussed that issue (at  Copenhagen airport). It would be nice to use it the future. But there's lack of tools (AFAIK) to read/write data packages.

**Comment by vpeil** [comment]
have a look at the branch https://github.com/OpenAPC/openapc-de/tree/ut_enrich

For the moment, I'm using @njahn82's R/isi_add.r script to produce the current table.

**Comment by cbroschinski** [comment]
As @vpeil pointed out correctly, **reading** the apc_de is not the problem (That's not what is was refering to when talking about "language agnosticism" - sorry about possible confusion), the problem is **writing**. The current quotation rules make it difficult to correctly implement tools or manually produce openAPC-compliant data without relying on the specific R scripts.
Two additional points:
- I've just created a new branch [full_quote_test](https://github.com/OpenAPC/openapc-de/tree/full_quote_test) which contains a full-quoted variant of the apc_de.csv. At least the README.Rmd does not have any problems in processing it. Haven't tested the github.io and reporting scripts yet, though.
- If (for the moment) someone needs to convert a csv file to the current R-style quotation, one may use the tool [csv_column_modification.py](https://github.com/OpenAPC/openapc-de/blob/python_dev/python/csv_column_modification.py) in the python_dev branch.
Given that you already have a valid APC csv file which just lacks the correct quotation, use

`python csv_column_modification.py CSV_FILE -e utf-8 -o -q tfftttttttttttttt copy`

to generate a file named "out.csv" with the correct R-style quotation.

**Comment by njahn82** [comment]
Thanks for making clear that the discussion is about a write and not a read problem. Even though I find it strange to write a conversion script, which adds complexity, `read.csv` seems to interpret the columns as intended. However, please bear in mind that it absolutely makes sense to be strict about quotation conventions in order to reduce data cleaning efforts before analyzing the data. When people are using `readr::read_csv` to load the spreadsheet, enquoted `NA` will be interpreted as character string and not as a missing value. So, while fixing our production pipeline, we are causing more trouble at least for those who want to analyse our data with R.

**Comment by vpeil** [comment]
ok, I've submitted the pull request. 

@cbroschinski can run this script on every update of the data set if he likes
